Repository hemareddy123/ProjectK-Soen6011summer2023, pull requests merged in 2023-07, with the labels that each got.

#19 Creation of user_stories_Sprint1 Issue #4 and Issue #7
  Sprint 1/user_stories_Sprint1.md
Labels: User Story

#26 Dikshant patch1
  Sprint 1/user_stories_Sprint1.md
Labels: User Story

#23 Added user stories for assigned issues
  Sprint 1/user_stories_Sprint1.md
Labels: User Story

#55 Create User Stories for the Current Sprint (Sprint 2)
  Sprint 2/user_stories_Sprint2.md
Labels: User Story

#74 Updated Project Approach
  README.md
Labels: documentation

#78 Removed unwanted and redundant files
  Sprint 2/code/EmployerProfile/App.js
  Sprint 2/code/EmployerProfile/Form.css
  Sprint 2/code/EmployerProfile/README.md
  Sprint 2/code/EmployerProfile/images/luke-chesser-IGtutkXikuc-unsplash.jpg
  Sprint 2/code/EmployerProfile/index.js
  Sprint 2/code/EmployerProfile/public/favicon.ico
  Sprint 2/code/EmployerProfile/public/index.html
  Sprint 2/code/EmployerProfile/public/logo192.png
  Sprint 2/code/EmployerProfile/public/logo512.png
  Sprint 2/code/EmployerProfile/public/manifest.json
  Sprint 2/code/EmployerProfile/public/robots.txt
  Sprint 2/code/static/images/background_job.jpeg
  Sprint 2/code/static/images/loginpagebackground.jpg
  Sprint 2/code/static/images/luke-chesser-pJadQetzTkI-unsplash (1).jpg
  Sprint 2/code/static/styles/dashboard.css
Labels: enhancement

#92 Upload resume new
  Sprint 3/code/Models/Student.py
  Sprint 3/code/Resource/StudentController.py
  Sprint 3/code/Resource/UserController.py
  Sprint 3/code/__pycache__/db.cpython-311.pyc
  Sprint 3/code/app.py
  Sprint 3/code/static/scripts/controllers.js
  Sprint 3/code/templates/studentProfile.html
  Sprint 3/code/templates/studentProfileForm.html
Labels: User Story, UI/UX, Back-end Dev, Task

#95 Fixed User's table on Admin Dashboard.
  Sprint 3/code/Models/User.py
  Sprint 3/code/Models/__pycache__/JobPosting.cpython-37.pyc
  Sprint 3/code/Models/__pycache__/Student.cpython-37.pyc
  Sprint 3/code/Models/__pycache__/User.cpython-37.pyc
  Sprint 3/code/Resource/AdminController.py
  Sprint 3/code/Resource/UserController.py
  Sprint 3/code/Resource/__pycache__/AdminController.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/EmpStudentController.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/JobPostController.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/StudentController.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/UserController.cpython-37.pyc
  Sprint 3/code/__pycache__/db.cpython-37.pyc
  Sprint 3/code/app.py
  Sprint 3/code/db.sqlite3
  Sprint 3/code/static/scripts/controllers.js
  Sprint 3/code/static/scripts/dashboard.js
  Sprint 3/code/templates/adminDashboard.html
Labels: enhancement, UI/UX, Back-end Dev

#96 Fixed the student creation
  Sprint 3/code/Models/User.py
  Sprint 3/code/app.py
Labels: bug, Back-end Dev

#102 Half Integration Completed with an Employer,job and student
  Sprint 3/code/Models/JobPosting.py
  Sprint 3/code/Models/Student.py
  Sprint 3/code/Models/User.py
  Sprint 3/code/Models/__pycache__/User.cpython-311.pyc
  Sprint 3/code/Resource/JobPostController.py
  Sprint 3/code/Resource/StudentController.py
  Sprint 3/code/Resource/UserController.py
  Sprint 3/code/app.py
  Sprint 3/code/static/scripts/controllers.js
  Sprint 3/code/templates/empDashboard.html
  Sprint 3/code/templates/studentDashboard.html
Labels: documentation, enhancement, UI/UX, Back-end Dev, Task

#103 Create User Stories with Task Breakdown for Sprint 3.
  Sprint 3/user_stories_tasks_Sprint3.md
Labels: User Story

#110 Initiated Unit testing
  .vscode/settings.json
  Sprint 3/code/Models/__pycache__/JobPosting.cpython-37.pyc
  Sprint 3/code/Models/__pycache__/Student.cpython-37.pyc
  Sprint 3/code/Models/__pycache__/User.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/AdminController.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/JobPostController.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/StudentController.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/UserController.cpython-37.pyc
  Sprint 3/code/__pycache__/app.cpython-37.pyc
  Sprint 3/code/db.sqlite3
  Sprint 3/code/tests/__pycache__/test_app.cpython-37-pytest-7.1.2.pyc
  Sprint 3/code/tests/test_app.py
Labels: Back-end Dev, Testing

#111 Add additional user stories tasks and risks | User-stories
  Sprint 3/user_stories_tasks_Sprint3.md
Labels: documentation, User Story

#113 Full Integration of Student,Employer and Job Posting
  Sprint 3/code/Resource/EmpStudentController.py
  Sprint 3/code/Resource/JobPostController.py
  Sprint 3/code/app.py
  Sprint 3/code/static/scripts/controllers.js
  Sprint 3/code/templates/empDashboard.html
Labels: enhancement, UI/UX, Back-end Dev

#115 Update User Stories Sprint 3 with corrected format
  Sprint 3/user_stories_tasks_Sprint3.md
Labels: documentation, User Story

#117 Bug Resolved - Status of student changes on selection by employer
  Sprint 3/code/Models/Student.py
  Sprint 3/code/Resource/EmpStudentController.py
  Sprint 3/code/Resource/StudentController.py
  Sprint 3/code/templates/studentDashboard.html
Labels: bug

#121 Admin feature - view all job postings, view all user and deleting the…
  Sprint 3/code/Resource/UserController.py
  Sprint 3/code/app.py
  Sprint 3/code/static/scripts/adminDashboard.js
  Sprint 3/code/static/scripts/controllers.js
  Sprint 3/code/static/scripts/dashboard.js
  Sprint 3/code/templates/adminDashboard.html
Labels: UI/UX, Back-end Dev, Task

#122 Admin can delete job postings too
  Sprint 3/code/Resource/JobPostController.py
Labels: UI/UX, Back-end Dev

#120 Added additional User stories for admin
  Sprint 3/user_stories_tasks_Sprint3.md
Labels: documentation, User Story
