Repository hemareddy123/ProjectK-Soen6011summer2023, pull requests merged in 2023-08, with the labels that each got.

#118 Updated test_app.py
  Sprint 3/code/Models/__pycache__/JobPosting.cpython-37.pyc
  Sprint 3/code/Models/__pycache__/Student.cpython-37.pyc
  Sprint 3/code/Models/__pycache__/User.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/AdminController.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/JobPostController.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/StudentController.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/UserController.cpython-37.pyc
  Sprint 3/code/__pycache__/app.cpython-37.pyc
  Sprint 3/code/db.sqlite3
  Sprint 3/code/db_queries/delete.py
  Sprint 3/code/tests/__pycache__/test_app.cpython-37-pytest-7.1.2.pyc
  Sprint 3/code/tests/test_app.py
Labels: Testing

#127 Update README.md
  README.md
Labels: documentation

#131 Added new unit tests
  Sprint 3/code/Models/JobPosting.py
  Sprint 3/code/Models/User.py
  Sprint 3/code/Models/__pycache__/JobPosting.cpython-37.pyc
  Sprint 3/code/Models/__pycache__/Student.cpython-37.pyc
  Sprint 3/code/Models/__pycache__/User.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/EmpStudentController.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/JobPostController.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/StudentController.cpython-37.pyc
  Sprint 3/code/Resource/__pycache__/UserController.cpython-37.pyc
  Sprint 3/code/__pycache__/app.cpython-37.pyc
  Sprint 3/code/db.sqlite3
  Sprint 3/code/tests/__pycache__/test_app.cpython-37-pytest-7.1.2.pyc
  Sprint 3/code/tests/test_app.py
Labels: Testing, Continuous Integration

#133 Backedn apis unit testing complete
  Sprint 3/code/db.sqlite3
  Sprint 3/code/tests/__pycache__/test_app.cpython-37-pytest-7.1.2.pyc
  Sprint 3/code/tests/test_app.py
Labels: Task, Testing, Continuous Integration

#134 Bug Fix for admin Web Page
  Sprint 3/code/templates/adminDashboard.html
Labels: bug

#135 Refactored Unit Testing file and CI workflow
  .github/workflows/CI-CD.yml
  Sprint 3/code/db.sqlite3
  Sprint 3/code/tests/__pycache__/test_app_units.cpython-37-pytest-7.1.2.pyc
  Sprint 3/code/tests/test_app_units.py
Labels: Back-end Dev, Testing, Continuous Integration

#136 Update CI-CD.yml
  .github/workflows/CI-CD.yml
Labels: bug, Continuous Integration

#146 Update CI-CD.yml
  .github/workflows/CI-CD.yml
Labels: Continuous Integration

#148 Chat feature main
  .github/workflows/CI-CD.yml
  Sprint 3/code/app.py
  Sprint 4/code/app.py
  Sprint 4/code/instance/db.sqlite3
  Sprint 4/code/tests/Rahul Sharam_resume.pdf
  Sprint 4/code/tests/test_app_units.py
  Sprint 4/requirements.txt
  archive/Sprint 2/.idea/.gitignore
  archive/Sprint 2/.idea/Sprint 2.iml
  archive/Sprint 2/.idea/misc.xml
  archive/Sprint 2/.idea/modules.xml
  archive/Sprint 2/.idea/vcs.xml
  archive/Sprint 2/README_Sprint2.md
  archive/Sprint 2/SQLcommands
  archive/Sprint 2/app.py
  archive/Sprint 2/static/images/loginpagebackground.jpg
  archive/Sprint 2/templates/login.html
Labels: Testing, Continuous Integration

#138 Create User Acceptance Tests #137
  Sprint 4/UserAcceptanceTests.md
Labels: documentation, Test Suites

#151 Update app.py
  Sprint 4/code/app.py
Labels: bug

#153 updated Readme and removed the unused file
  README.md
  Screenshot 2023-08-09 at 10.45.46 PM.png
  carrer.html
  style.css
Labels: documentation

#157 Uploaded Class Diagram
  Class Diagram.jpg
Labels: documentation
